name: beatauto
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-api-python-client
      - pyyaml
      - python-dotenv
      - requests
      - pillow
      - ffmpeg-python
      - librosa
      - soundfile
      - google-api-python-client
      - google-auth-oauthlib
      - playwright
      - google-generativeai
